"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import {Header} from '@/components/Header'
import { Footer } from "@/components/Footer";
import styles from './layout.module.css'
import "../node_modules/bootstrap/dist/css/bootstrap.css";
import { useState, useEffect } from "react";


import { Menu } from "@/components/Menu";
import plat from '@/public/product-1.jpg'
import { Connexion } from "@/components/Connexion";
import { Inscription } from "@/components/Inscription";
import {Test} from '@/components/test'
const inter = Inter({ subsets: ["latin"] });
import {CategorieGestion} from '@/components/CategorieGestion'
import { ProduitGestion } from "@/components/ProduitGEstion";
import { RoleGestion } from "@/components/GestionRole";
import {ListeCategories}from "@/components/ListeCategorie"
import { CommandeGestion } from "@/components/CommandeGestion";
import {CommandeComplette} from "@/components/CommandeComplette"
import { Verification } from "@/components/Verification";

import { ListeMenu } from "@/components/ListeMenu";
import { DashBord } from "@/components/dashBord";
import { ListeCategoriesAcc } from "@/components/ListeCatAcc";

/*
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {
  const [page, setPage] = useState('accueil')
  const [entete,SetEntete]= useState('default')
/*
  useEffect(() => {
    const handleUserChange = () => {
      const Token = localStorage.getItem("clientToken");
      
      const userDataString = localStorage.getItem("user");
      if (Token && userDataString) {
        
        if (userDataString) {
          const userData = JSON.parse(userDataString);
          const number = userData?.type_utilisateur?.niveau;
          
          if (number===0){
            SetEntete('opt1')
            setPage('menu')
          }else if(number>0){
            SetEntete('opt2')
            setPage('gestion')
          }

        }
        
      }else if (!Token && userDataString){setPage('verification')}else if(!Token && !userDataString)  {
//setPage('accueil')
      }

     
    };

    handleUserChange()
  }


  )

*/

  return (
    <html lang="en">
      <body className={inter.className + " " + styles.body}>
        <Header setPage={setPage}></Header>
        
        <main className={styles.main} >
          
          {page === 'inscription' ? 
          <Inscription setPage={setPage} />
        : page === 'connexion' ?
          <Connexion setPage={setPage}/>
        : page === 'menu' ?
          <ListeCategories />
        :page === 'gestion' ?
        <DashBord  setPage={setPage}/>
        : page === 'accueil' ? <ListeCategoriesAcc setPage={setPage} />
        :
        page === 'verification' ? <Verification />
        :
        page === 'categorie' ? <CategorieGestion />
        :
        page === 'produit' ? <ProduitGestion />
        :
        page === 'role' ? <RoleGestion />
        :
        page === 'complette' ? <CommandeComplette />
        :
        page === 'commande' ? <CommandeGestion />
        :
        page === 'utilisateur' ? <utili />
        :
          <div>404 - Not Found</div>
        }



        

      
    </main>
    <Footer></Footer>
    
    </body>
    </html>
  );
}
