"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import {Header} from '@/components/Header'
import { Footer } from "@/components/Footer";
import styles from './layout.module.css'
import "../node_modules/bootstrap/dist/css/bootstrap.css";
import { useState, useEffect } from "react";



const inter = Inter({ subsets: ["latin"] });


/*
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {

  const [entete,SetEntete]= useState('default')

  return (
    <html lang="en">
      <body className={inter.className + " " + styles.body}>
        <Header ></Header>
        
        <main className={styles.main} >
          
          {children}



        

      
    </main>
    <Footer></Footer>
    
    </body>
    </html>
  );
}
